# Generated by Django 4.2.30 on 2026-06-09 23:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_pdv_id', models.IntegerField(blank=True, help_text='ID do pdv.Produto correspondente (opcional)', null=True)),
                ('nome', models.CharField(max_length=120)),
                ('rendimento', models.PositiveIntegerField(default=1, help_text='Quantas unidades a receita produz')),
                ('embalagem_custo', models.DecimalField(decimal_places=2, default=Decimal('0.08'), help_text='Custo da embalagem por unidade (R$)', max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('unidade_compra', models.CharField(help_text='Ex: 1kg, 500g, 30 unidades', max_length=40)),
                ('quantidade_compra', models.DecimalField(decimal_places=3, help_text='Quantidade na embalagem de compra (em g, ml ou un)', max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('g', 'Gramas'), ('ml', 'Mililitros'), ('un', 'Unidade'), ('kg', 'Quilograma'), ('l', 'Litro')], default='g', max_length=5)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matéria-Prima',
                'verbose_name_plural': 'Matérias-Primas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_meta', models.DecimalField(decimal_places=2, default=40000, max_digits=10)),
                ('despesa_fixa_mensal', models.DecimalField(decimal_places=2, default=17000, max_digits=10)),
                ('despesa_variavel_pct', models.DecimalField(decimal_places=4, default=Decimal('0.425'), help_text='Percentual das despesas variáveis sobre o preço de venda (ex: 0.425 = 42,5%)', max_digits=5)),
                ('margem_lucro_esperada_pct', models.DecimalField(decimal_places=4, default=Decimal('0.30'), help_text='Margem de lucro esperada sobre a venda (ex: 0.30 = 30%)', max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetros do Negócio',
            },
        ),
        migrations.CreateModel(
            name='SnapshotPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('dados', models.JSONField(help_text="{'produto_id': preco_anterior, ...}")),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revertido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Snapshot de Preços',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade usada na receita (mesma unidade da matéria-prima)', max_digits=10)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fichas.fichatecnica')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fichas.materiaprima')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'unique_together': {('ficha', 'materia_prima')},
            },
        ),
    ]
