# Generated by Django 4.2.30 on 2026-07-16 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Limite mínimo para disparo de alerta de estoque baixo. 0 = sem alerta', max_digits=10),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Saldo atual em estoque, na unidade_medida. Derivado — nunca editar direto, sempre via estoque.MovimentoEstoque.registrar()', max_digits=10),
        ),
    ]
