# Generated by Django 4.2.30 on 2026-07-16 23:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0002_materiaprima_estoque_minimo_and_more'),
        ('pdv', '0007_produto_estoque_minimo_produto_modo_estoque_and_more'),
        ('usuarios', '0002_usuario_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_minimo_padrao', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Sugerido ao cadastrar item novo sem mínimo definido (não sobrescreve os já cadastrados)', max_digits=10)),
                ('alerta_whatsapp_ativo', models.BooleanField(default=True)),
                ('alerta_repetir_diariamente', models.BooleanField(default=True, help_text='Enquanto o item continuar abaixo do mínimo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Estoque',
            },
        ),
        migrations.CreateModel(
            name='TelefoneAlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome/label (opcional)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telefone de Alerta de Estoque',
                'verbose_name_plural': 'Telefones de Alerta de Estoque',
                'ordering': ['nome', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzida', models.DecimalField(decimal_places=3, help_text='Em unidades do produto (não da ficha)', max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='fichas.fichatecnica')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produções',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('entrada_compra', 'Entrada — compra'), ('entrada_producao', 'Entrada — produção'), ('saida_producao', 'Saída — produção'), ('saida_venda', 'Saída — venda'), ('ajuste_inventario', 'Ajuste — inventário')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Sempre positivo — o efeito no saldo vem de tipo_movimento, não do sinal deste campo', max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('custo_unitario_snapshot', models.DecimalField(blank=True, decimal_places=4, help_text='Preserva o custo no momento do movimento — não recalcula histórico se o preço mudar depois', max_digits=10, null=True)),
                ('origem_tipo', models.CharField(blank=True, help_text="'pedido_pdv' | 'pedido_ifood' | 'evento' | 'producao' | 'nota_fiscal' | 'manual'", max_length=20, null=True)),
                ('origem_id', models.IntegerField(blank=True, help_text='FK fraca pro registro de origem — evita dependência circular entre apps (mesmo padrão de FichaTecnica.produto_pdv_id)', null=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, help_text='Null quando o movimento vem de signal automático (venda)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='fichas.materiaprima')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='pdv.produto')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['origem_tipo', 'origem_id'], name='estoque_mov_origem__552c1e_idx'), models.Index(fields=['materia_prima', '-criado_em'], name='estoque_mov_materia_9c57c3_idx'), models.Index(fields=['produto', '-criado_em'], name='estoque_mov_produto_fa9ece_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstoqueEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('materia_prima', 'Insumo'), ('produto', 'Produto')], max_length=20)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviados', to='fichas.materiaprima')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviados', to='pdv.produto')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque Enviado',
                'verbose_name_plural': 'Alertas de Estoque Enviados',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['materia_prima', 'produto', '-enviado_em'], name='estoque_ale_materia_5bed62_idx')],
            },
        ),
    ]
