# Generated by Django 4.2.30 on 2026-07-17 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_auth_token'),
        ('pdv', '0007_produto_estoque_minimo_produto_modo_estoque_and_more'),
        ('fichas', '0002_materiaprima_estoque_minimo_and_more'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracao_ia_ativa', models.BooleanField(default=True, help_text='Permite desativar o fallback de IA sem tocar código')),
                ('modelo', models.CharField(default='claude-sonnet-5', max_length=40)),
                ('timeout_segundos', models.PositiveIntegerField(default=30)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de IA',
            },
        ),
        migrations.CreateModel(
            name='ImportacaoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='estoque/notas_fiscais/%Y/%m/')),
                ('metodo_extracao', models.CharField(choices=[('xml', 'XML da NF-e'), ('texto_pdf', 'Texto do PDF'), ('ia', 'IA multimodal'), ('falhou', 'Falhou')], max_length=15)),
                ('numero_nota', models.CharField(blank=True, default='', max_length=50)),
                ('fornecedor_nome', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('em_revisao', 'Em revisão'), ('confirmada', 'Confirmada'), ('descartada', 'Descartada')], default='em_revisao', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Importação de Nota Fiscal',
                'verbose_name_plural': 'Importações de Nota Fiscal',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_extraida', models.CharField(max_length=300)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status_match', models.CharField(choices=[('encontrado', 'Encontrado'), ('revisar', 'Revisar')], max_length=12)),
                ('descartado', models.BooleanField(default=False)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.importacaonotafiscal')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota_importada', to='fichas.materiaprima')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota_importada', to='pdv.produto')),
            ],
            options={
                'verbose_name': 'Item de Nota Importada',
                'verbose_name_plural': 'Itens de Nota Importada',
                'ordering': ['id'],
            },
        ),
    ]
