# Generated by Django 4.2.30 on 2026-07-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_configuracaoia_importacaonotafiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaonotafiscal',
            name='fornecedor_cnpj',
            field=models.CharField(blank=True, default='', help_text='Capturado pela cascata de extração (emit/CNPJ no XML; best-effort em PDF/IA) — usado pra resolver/criar financeiro.Fornecedor na confirmação (Fase 5 do Financeiro).', max_length=20),
        ),
    ]
