# Generated by Django 4.2.30 on 2026-05-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evento',
            new_name='eventos_eve_data_ev_f5036c_idx',
            old_name='eventos_eve_data_ev_idx',
        ),
        migrations.RenameIndex(
            model_name='evento',
            new_name='eventos_eve_cliente_5c58dc_idx',
            old_name='eventos_eve_cliente_idx',
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco_avulso',
            field=models.CharField(blank=True, default='', help_text='Endereço livre quando não for usar um local cadastrado', max_length=400),
        ),
    ]
