# Generated by Django 4.2.30 on 2026-06-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pdv', '0002_rename_pdv_pedido_status_idx_pdv_pedidop_status_044627_idx_and_more'),
        ('eventos', '0002_rename_eventos_eve_data_ev_idx_eventos_eve_data_ev_f5036c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_telefone', models.CharField(blank=True, default='', max_length=30)),
                ('tipo_evento', models.CharField(blank=True, choices=[('casamento', 'Casamento'), ('formatura', 'Formatura'), ('aniversario', 'Aniversário'), ('corporativo', 'Corporativo'), ('batizado', 'Batizado'), ('cha', 'Chá de bebê / revelação'), ('outro', 'Outro')], default='', max_length=30)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, help_text='Data limite de validade do orçamento', null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('expirado', 'Expirado'), ('convertido', 'Convertido')], db_index=True, default='rascunho', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='clientes.cliente')),
                ('evento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_origem', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, default='', max_length=300)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='eventos.orcamento')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='pdv.produto')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status', 'criado_em'], name='eventos_orc_status_2dc0da_idx'),
        ),
    ]
