# Generated by Django 4.2.30 on 2026-07-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='bairro_entrega',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='bairro_entrega',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='endereco_avulso',
            field=models.CharField(blank=True, default='', help_text='Endereço livre quando não for usar um local cadastrado', max_length=400),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='eventos.localevento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_entrega',
            field=models.CharField(choices=[('retirada_loja', 'Retirada na loja'), ('entrega_local', 'Entrega no local da festa')], default='retirada_loja', max_length=20),
        ),
    ]
