# Generated by Django 4.2.30 on 2026-07-05 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado_civil_cliente_nacionalidade_and_more'),
        ('eventos', '0004_evento_bairro_entrega_evento_taxa_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social_contratada', models.CharField(blank=True, default='Arretado Doces', max_length=200)),
                ('cnpj_contratada', models.CharField(blank=True, default='', max_length=20)),
                ('endereco_contratada', models.CharField(blank=True, default='', max_length=400)),
                ('representante_nome', models.CharField(blank=True, default='', max_length=200)),
                ('representante_nacionalidade', models.CharField(blank=True, default='brasileiro', max_length=50)),
                ('representante_estado_civil', models.CharField(blank=True, default='', max_length=20)),
                ('representante_profissao', models.CharField(blank=True, default='', max_length=100)),
                ('representante_rg', models.CharField(blank=True, default='', max_length=20)),
                ('representante_cpf', models.CharField(blank=True, default='', max_length=14)),
                ('representante_endereco', models.CharField(blank=True, default='', max_length=400)),
                ('percentual_sinal', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('prazo_quitacao_dias', models.PositiveIntegerField(default=7, help_text='Dias antes do evento')),
                ('multa_inadimplencia_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('juros_mora_pct_mes', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('prazo_personalizacao_dias', models.PositiveIntegerField(default=15)),
                ('prazo_aumento_quantidade_dias', models.PositiveIntegerField(default=15)),
                ('prazo_aviso_rescisao_dias', models.PositiveIntegerField(default=30)),
                ('multa_rescisao_acima_60_dias_pct', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('multa_rescisao_30_60_dias_pct', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('multa_rescisao_abaixo_30_dias_pct', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('multa_rescisao_abaixo_7_dias_pct', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('prazo_devolucao_dias', models.PositiveIntegerField(default=30)),
                ('foro_comarca', models.CharField(blank=True, default='Teresina', max_length=100)),
                ('foro_estado', models.CharField(blank=True, default='Piauí', max_length=100)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Contrato',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('gerado', 'Gerado'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], db_index=True, default='gerado', max_length=20)),
                ('contratante_nome', models.CharField(max_length=200)),
                ('contratante_nacionalidade', models.CharField(max_length=50)),
                ('contratante_profissao', models.CharField(blank=True, default='', max_length=100)),
                ('contratante_rg', models.CharField(blank=True, default='', max_length=20)),
                ('contratante_cpf', models.CharField(max_length=14)),
                ('contratante_estado_civil', models.CharField(blank=True, default='', max_length=20)),
                ('contratante_endereco', models.CharField(max_length=400)),
                ('data_evento', models.DateField()),
                ('hora_evento', models.TimeField(blank=True, null=True)),
                ('local_evento', models.CharField(blank=True, default='', max_length=400)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_sinal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_sinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_quitacao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='clientes.cliente')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='eventos.evento')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='eventos.orcamento')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
