# Generated by Django 4.2.30 on 2026-07-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_configuracaocontrato_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contratante_rg_orgao_emissor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='cnpj_contratada',
            field=models.CharField(blank=True, default='29.977.080/0001-11', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='endereco_contratada',
            field=models.CharField(blank=True, default='Avenida João Antônio Leitão, nº 3733, Bairro Piçarreira, CEP 64.055-400, Teresina/PI', max_length=400),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='representante_cpf',
            field=models.CharField(blank=True, default='081.465.044-93', max_length=14),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='representante_endereco',
            field=models.CharField(blank=True, default='Rua Vereador Edmundo Genuíno de Oliveira, nº 2945, apto 101, Bairro São Cristóvão, CEP 64.055-030, Teresina/PI', max_length=400),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='representante_estado_civil',
            field=models.CharField(blank=True, default='casado', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='representante_nome',
            field=models.CharField(blank=True, default='Edvan Lima Silva', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='representante_profissao',
            field=models.CharField(blank=True, default='biomédico', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='representante_rg',
            field=models.CharField(blank=True, default='3158399 SSP-PB', max_length=20),
        ),
    ]
