# Generated by Django 4.2.30 on 2026-07-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_contrato_contratante_rg_orgao_emissor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemInspiracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='orcamentos/inspiracao/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_inspiracao', to='eventos.orcamento')),
            ],
            options={
                'verbose_name': 'Imagem de Inspiração',
                'ordering': ['criado_em'],
            },
        ),
    ]
