# Generated by Django 4.2.30 on 2026-07-10 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_imageminspiracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pago', max_length=20)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Pagamento de Evento',
                'verbose_name_plural': 'Pagamentos de Evento',
                'ordering': ['data_pagamento', 'criado_em'],
            },
        ),
    ]
