# Generated by Django 4.2.30 on 2026-07-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_backfill_pagamentos_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoevento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='eventos/comprovantes/%Y/%m/'),
        ),
    ]
