# Generated by Django 4.2.30 on 2026-07-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_pagamentoevento_comprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAlertaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo_pagamento', models.BooleanField(default=True, verbose_name='Alerta de pagamento pendente ativo')),
                ('dias_antes_pagamento', models.PositiveIntegerField(default=10, verbose_name='Disparar a partir de quantos dias antes do evento')),
                ('repetir_pagamento_dias', models.PositiveIntegerField(default=1, verbose_name='Repetir a cada quantos dias (enquanto não pago)')),
                ('ativo_entrega', models.BooleanField(default=True, verbose_name='Alerta de local/horário de entrega ativo')),
                ('dias_antes_entrega', models.PositiveIntegerField(default=30, verbose_name='Disparar a partir de quantos dias antes do evento')),
                ('repetir_entrega_dias', models.PositiveIntegerField(default=5, verbose_name='Repetir a cada quantos dias')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Alertas de Evento',
            },
        ),
        migrations.CreateModel(
            name='TelefoneAlertaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome/label (opcional)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telefone de Alerta de Evento',
                'verbose_name_plural': 'Telefones de Alerta de Evento',
                'ordering': ['nome', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEventoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagamento_pendente', 'Pagamento pendente'), ('aviso_entrega', 'Aviso de entrega')], max_length=30)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviados', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Alerta de Evento Enviado',
                'verbose_name_plural': 'Alertas de Evento Enviados',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['evento', 'tipo', '-enviado_em'], name='eventos_ale_evento__061a21_idx')],
            },
        ),
    ]
