# Generated by Django 4.2.30 on 2026-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_configuracaoalertaevento_telefonealertaevento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocontrato',
            name='instagram_contratada',
            field=models.CharField(blank=True, default='@arretadodoces', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracaocontrato',
            name='telefone_contratada',
            field=models.CharField(blank=True, default='(86) 99816-4324', max_length=20),
        ),
    ]
