# Generated by Django 4.2.30 on 2026-08-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_configuracaocontrato_instagram_contratada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_pagamento_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pagamento_entrada',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('outro', 'Outro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacao_entrada',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_entrada_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
