# Generated by Django 4.2.30 on 2026-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_contrato_pagamento_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemevento',
            name='natureza',
            field=models.CharField(choices=[('venda', 'Venda'), ('brinde', 'Brinde'), ('permuta', 'Permuta')], default='venda', max_length=10),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='natureza',
            field=models.CharField(choices=[('venda', 'Venda'), ('brinde', 'Brinde'), ('permuta', 'Permuta')], default='venda', max_length=10),
        ),
    ]
