# Generated by Django 4.2.30 on 2026-09-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_brindes_permutas_natureza_fase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageminspiracao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_inspiracao_diretas', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='imageminspiracao',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_inspiracao', to='eventos.orcamento'),
        ),
        migrations.AddConstraint(
            model_name='imageminspiracao',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('evento__isnull', True), ('orcamento__isnull', False)), models.Q(('evento__isnull', False), ('orcamento__isnull', True)), _connector='OR'), name='imageminspiracao_exatamente_um_dono'),
        ),
    ]
