# Generated by Django 4.2.30 on 2026-09-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_imageminspiracao_evento_direto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='observacoes_cozinha',
            field=models.TextField(blank=True, default=''),
        ),
    ]
