# Generated by Django 4.2.30 on 2026-09-14 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado_civil_cliente_nacionalidade_and_more'),
        ('eventos', '0016_evento_observacoes_cozinha'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('valor_total_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_entrega_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itens_snapshot', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_contrato', to='clientes.cliente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='eventos.contrato')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Aditivo de Contrato',
                'verbose_name_plural': 'Aditivos de Contrato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
