# Generated by Django 4.2.30 on 2026-07-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Nome do usuário (snapshot)')),
                ('acao', models.CharField(choices=[('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('logout', 'Logout'), ('usuario_criado', 'Usuário criado'), ('usuario_editado', 'Usuário editado'), ('usuario_removido', 'Usuário removido'), ('permissao_alterada', 'Permissão/role alterada'), ('senha_redefinida', 'Senha redefinida')], max_length=40, verbose_name='Ação')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='usuarios.usuario', verbose_name='Usuário (ator)')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'auditoria_logs',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['acao'], name='auditoria_l_acao_1bbeeb_idx'), models.Index(fields=['-criado_em'], name='auditoria_l_criado__811656_idx'), models.Index(fields=['usuario'], name='auditoria_l_usuario_191308_idx')],
            },
        ),
    ]
