# Generated by Django 4.2.30 on 2026-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_logauditoria_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('logout', 'Logout'), ('usuario_criado', 'Usuário criado'), ('usuario_editado', 'Usuário editado'), ('usuario_removido', 'Usuário removido'), ('permissao_alterada', 'Permissão/role alterada'), ('senha_redefinida', 'Senha redefinida'), ('pagamento_registrado', 'Pagamento registrado'), ('pagamento_removido', 'Pagamento removido'), ('contrato_emitido', 'Contrato emitido'), ('contrato_enviado', 'Contrato enviado'), ('ajuste_linear_aplicado', 'Ajuste linear de preços aplicado'), ('ajuste_linear_desfeito', 'Ajuste linear de preços desfeito'), ('preco_materia_atualizado', 'Preço de matéria-prima atualizado'), ('parametros_negocio_alterados', 'Parâmetros de negócio alterados')], max_length=40, verbose_name='Ação'),
        ),
    ]
