# Generated by Django 4.2.30 on 2026-07-13 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_auth_token'),
        ('auditoria', '0006_alter_logauditoria_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('logout', 'Logout'), ('usuario_criado', 'Usuário criado'), ('usuario_editado', 'Usuário editado'), ('usuario_removido', 'Usuário removido'), ('permissao_alterada', 'Permissão/role alterada'), ('senha_redefinida', 'Senha redefinida'), ('pagamento_registrado', 'Pagamento registrado'), ('pagamento_removido', 'Pagamento removido'), ('contrato_emitido', 'Contrato emitido'), ('contrato_enviado', 'Contrato enviado'), ('ajuste_linear_aplicado', 'Ajuste linear de preços aplicado'), ('ajuste_linear_desfeito', 'Ajuste linear de preços desfeito'), ('preco_materia_atualizado', 'Preço de matéria-prima atualizado'), ('parametros_negocio_alterados', 'Parâmetros de negócio alterados'), ('config_contrato_alterada', 'Configuração de contrato alterada'), ('config_entrega_alterada', 'Configuração de entrega alterada'), ('config_whatsapp_alterada', 'Configuração de WhatsApp alterada'), ('registro_excluido', 'Registro excluído'), ('registro_criado', 'Registro criado'), ('registro_atualizado', 'Registro atualizado'), ('status_alterado', 'Status alterado'), ('item_adicionado', 'Item adicionado'), ('orcamento_convertido_em_evento', 'Orçamento convertido em evento')], max_length=40, verbose_name='Ação'),
        ),
        migrations.CreateModel(
            name='PresencaEdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Presença de Edição',
                'verbose_name_plural': 'Presenças de Edição',
                'db_table': 'auditoria_presenca_edicao',
                'indexes': [models.Index(fields=['model', 'objeto_id'], name='auditoria_p_model_895efc_idx')],
                'unique_together': {('usuario', 'model', 'objeto_id')},
            },
        ),
    ]
