# Generated by Django 4.2.30 on 2026-07-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0008_alter_logauditoria_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('logout', 'Logout'), ('usuario_criado', 'Usuário criado'), ('usuario_editado', 'Usuário editado'), ('usuario_removido', 'Usuário removido'), ('permissao_alterada', 'Permissão/role alterada'), ('senha_redefinida', 'Senha redefinida'), ('pagamento_registrado', 'Pagamento registrado'), ('pagamento_removido', 'Pagamento removido'), ('contrato_emitido', 'Contrato emitido'), ('contrato_enviado', 'Contrato enviado'), ('ajuste_linear_aplicado', 'Ajuste linear de preços aplicado'), ('ajuste_linear_desfeito', 'Ajuste linear de preços desfeito'), ('preco_materia_atualizado', 'Preço de matéria-prima atualizado'), ('parametros_negocio_alterados', 'Parâmetros de negócio alterados'), ('config_contrato_alterada', 'Configuração de contrato alterada'), ('config_entrega_alterada', 'Configuração de entrega alterada'), ('config_whatsapp_alterada', 'Configuração de WhatsApp alterada'), ('config_alerta_evento_alterada', 'Configuração de alertas de evento alterada'), ('registro_excluido', 'Registro excluído'), ('registro_criado', 'Registro criado'), ('registro_atualizado', 'Registro atualizado'), ('status_alterado', 'Status alterado'), ('item_adicionado', 'Item adicionado'), ('orcamento_convertido_em_evento', 'Orçamento convertido em evento'), ('entrada_estoque_registrada', 'Entrada de estoque registrada'), ('ajuste_inventario_registrado', 'Ajuste de inventário registrado'), ('producao_registrada', 'Produção registrada'), ('config_estoque_alterada', 'Configuração de estoque alterada')], max_length=40, verbose_name='Ação'),
        ),
    ]
