# Generated by Django 4.2.30 on 2026-05-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pedidoifood',
            new_name='ifood_pedid_status_d1a98b_idx',
            old_name='pedido_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pedidoifood',
            new_name='ifood_pedid_criado__30ed84_idx',
            old_name='pedido_criado_em_idx',
        ),
        migrations.RenameIndex(
            model_name='pedidoifood',
            new_name='ifood_pedid_cliente_2e9d75_idx',
            old_name='pedido_cliente_ifood_idx',
        ),
        migrations.AlterField(
            model_name='configuracaoifood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracaoifood',
            name='polling_intervalo',
            field=models.IntegerField(default=30, help_text='Segundos entre polls'),
        ),
        migrations.AlterField(
            model_name='eventopollingifood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itempedidoifood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedidoifood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
