# Generated by Django 4.2.30 on 2026-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0002_rename_pedido_status_idx_ifood_pedid_status_d1a98b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoifood',
            name='agendamento_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='benefits_raw',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='cliente_cpf',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='negociacao_descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='negociacao_pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='negociacao_tipo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='observacao_pedido',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='payment_brand',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='payment_prepaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='payment_troco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
