# Generated by Django 4.2.30 on 2026-06-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0005_configuracaoifood_auto_despachar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoifood',
            name='delivery_mode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
