# Generated by Django 4.2.30 on 2026-08-11 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_criar_empresa_padrao'),
        ('ifood', '0006_delivery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoifood',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_ifood', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_ifood', to='empresas.empresa'),
        ),
    ]
