# Generated by Django 4.2.30 on 2026-05-24 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoUnificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('ifood', 'iFood'), ('anotaai', 'Anota AI'), ('pdv', 'PDV Próprio')], db_index=True, max_length=20)),
                ('origem_id', models.PositiveIntegerField(db_index=True, help_text='PK do pedido no app de origem (ifood.PedidoIFood, etc.)')),
                ('numero', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_preparo', 'Em preparo'), ('pronto', 'Pronto / Aguardando retirada'), ('em_entrega', 'Em entrega'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('status_original', models.CharField(blank=True, default='', max_length=50)),
                ('tipo', models.CharField(choices=[('delivery', 'Delivery'), ('retirada', 'Retirada'), ('mesa', 'Mesa / Indoor'), ('balcao', 'Balcão')], default='delivery', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagamento', models.CharField(blank=True, default='', max_length=100)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_telefone', models.CharField(blank=True, default='', max_length=30)),
                ('endereco_entrega', models.JSONField(blank=True, default=dict)),
                ('itens_snapshot', models.JSONField(blank=True, default=list, help_text='Snapshot dos itens no momento do pedido')),
                ('pedido_em', models.DateTimeField(db_index=True, help_text='Data/hora em que o pedido foi criado no canal de origem')),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_unificados', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pedido Unificado',
                'verbose_name_plural': 'Pedidos Unificados',
                'ordering': ['-pedido_em'],
                'indexes': [models.Index(fields=['cliente', '-pedido_em'], name='pedidos_ped_cliente_ddbfbf_idx'), models.Index(fields=['canal', 'status'], name='pedidos_ped_canal_7a7b0d_idx'), models.Index(fields=['pedido_em'], name='pedidos_ped_pedido__101b86_idx')],
                'unique_together': {('canal', 'origem_id')},
            },
        ),
    ]
