# Generated by Django 4.2.30 on 2026-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidounificado',
            name='canal',
            field=models.CharField(choices=[('ifood', 'iFood'), ('anotaai', 'Anota AI'), ('pdv', 'PDV Próprio'), ('eventos', 'Eventos')], db_index=True, max_length=20),
        ),
    ]
