# Generated by Django 4.2.30 on 2026-08-11 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_criar_empresa_padrao'),
        ('pedidos', '0002_alter_pedidounificado_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidounificado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_unificados', to='empresas.empresa'),
        ),
    ]
