# Generated by Django 4.2.30 on 2026-10-07 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0017_aditivocontrato'),
        ('notificacoes', '0012_alter_historicomensagem_tipo'),
        ('usuarios', '0004_vincular_usuarios_empresa_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Envio automático ligado')),
                ('ativo_desde', models.DateField(blank=True, null=True, verbose_name='Ligado desde')),
                ('limite_lembrete', models.IntegerField(default=-7, validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)], verbose_name='Data limite (fronteira lembrete × cobrança)')),
                ('dias_semana_envio', models.JSONField(default=list, verbose_name='Dias da semana com envio')),
                ('chave_pix', models.CharField(blank=True, default='', max_length=120, verbose_name='Chave Pix')),
                ('favorecido_pix', models.CharField(blank=True, default='', max_length=120, verbose_name='Favorecido do Pix')),
                ('telefone_contato', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone de contato')),
                ('intervalo_envio_segundos', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Intervalo entre envios (segundos)')),
                ('notificar_equipe_ultima_etapa', models.BooleanField(default=True, verbose_name='Avisar a equipe quando a última etapa é enviada sem pagamento')),
                ('msg_prazo_hoje_ativo', models.BooleanField(default=True, verbose_name='Mensagem "prazo vence hoje" ativa')),
                ('msg_prazo_hoje', models.TextField(default='Oi, {primeiro_nome}! Passando para lembrar que hoje é o prazo que combinamos para o saldo do evento {numero_evento}: *R$ {saldo}*.\nPix: {chave_pix}\nObrigado! 💛', verbose_name='Mensagem "prazo vence hoje"')),
                ('msg_prazo_vencido_ativo', models.BooleanField(default=True, verbose_name='Mensagem "prazo venceu" ativa')),
                ('msg_prazo_vencido', models.TextField(default='Olá, {primeiro_nome}. O prazo combinado ({prazo_combinado}) para o saldo de *R$ {saldo}* do evento {numero_evento} venceu e ainda não identificamos o pagamento.\nPode nos dar um retorno?\nPix: {chave_pix}', verbose_name='Mensagem "prazo venceu"')),
                ('msg_ligacao_nao_atendida_ativo', models.BooleanField(default=False, verbose_name='Mensagem "tentamos te ligar" ativa')),
                ('msg_ligacao_nao_atendida', models.TextField(default='Oi, {primeiro_nome}! Tentamos falar com você por telefone sobre o saldo do evento {numero_evento} (*R$ {saldo}*).\nQuando puder, nos chame por aqui ou no {telefone_empresa}. Obrigado!', verbose_name='Mensagem "tentamos te ligar"')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Cobrança',
            },
        ),
        migrations.CreateModel(
            name='EnvioCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lembrete', 'Lembrete'), ('cobranca', 'Cobrança'), ('prazo_hoje', 'Prazo combinado vence hoje'), ('prazo_vencido', 'Prazo combinado venceu'), ('ligacao_nao_atendida', 'Ligação não atendida')], max_length=20)),
                ('dias_etapa', models.IntegerField(blank=True, null=True)),
                ('rotulo_etapa', models.CharField(blank=True, default='', max_length=5)),
                ('data_evento_referencia', models.DateField()),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falha'), ('pulada', 'Pulada')], max_length=10)),
                ('motivo_pulada', models.CharField(blank=True, choices=[('atraso', 'Atraso (etapa mais antiga pulada em favor da mais recente)'), ('pausa', 'Pausa vigente'), ('mesmo_dia', 'Já saiu outra mensagem no mesmo dia')], default='', max_length=10)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('mensagem_renderizada', models.TextField(blank=True, default='')),
                ('saldo_no_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Envio de Cobrança',
                'verbose_name_plural': 'Envios de Cobrança',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EtapaRegua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)], verbose_name='Dias em relação à data do evento')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa da Régua de Cobrança',
                'verbose_name_plural': 'Etapas da Régua de Cobrança',
                'ordering': ['dias'],
            },
        ),
        migrations.CreateModel(
            name='LigacaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendente_nome', models.CharField(blank=True, default='', max_length=150)),
                ('telefone_discado', models.CharField(max_length=30)),
                ('atendeu', models.BooleanField()),
                ('prazo_pagamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('registrado_por_nome', models.CharField(blank=True, default='', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligacoes_cobranca_atendidas', to='usuarios.usuario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ligacoes_cobranca', to='eventos.evento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligacoes_cobranca_registradas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Ligação de Cobrança',
                'verbose_name_plural': 'Ligações de Cobrança',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PausaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pausado_ate', models.DateField(verbose_name='Pausado até')),
                ('motivo', models.CharField(max_length=300)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('ligacao', 'Via ligação')], default='manual', max_length=10)),
                ('criado_por_nome', models.CharField(blank=True, default='', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('encerrada_por_nome', models.CharField(blank=True, default='', max_length=150)),
                ('motivo_encerramento', models.CharField(blank=True, default='', max_length=300)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pausas_cobranca_criadas', to='usuarios.usuario')),
                ('encerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pausas_cobranca_encerradas', to='usuarios.usuario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pausas_cobranca', to='eventos.evento')),
                ('ligacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pausa_criada', to='cobranca.ligacaocobranca')),
            ],
            options={
                'verbose_name': 'Pausa de Cobrança',
                'verbose_name_plural': 'Pausas de Cobrança',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='etaparegua',
            constraint=models.UniqueConstraint(fields=('dias',), name='uniq_etapa_regua_dias'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='cobranca.etaparegua'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_cobranca', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='historico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_cobranca', to='notificacoes.historicomensagem'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='ligacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='cobranca.ligacaocobranca'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='pausa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='cobranca.pausacobranca'),
        ),
        migrations.AddIndex(
            model_name='pausacobranca',
            index=models.Index(fields=['evento', '-criado_em'], name='cobranca_pa_evento__dec357_idx'),
        ),
        migrations.AddIndex(
            model_name='ligacaocobranca',
            index=models.Index(fields=['evento', '-data_hora'], name='cobranca_li_evento__195624_idx'),
        ),
        migrations.AddIndex(
            model_name='enviocobranca',
            index=models.Index(fields=['evento', '-criado_em'], name='cobranca_en_evento__063ef1_idx'),
        ),
        migrations.AddConstraint(
            model_name='enviocobranca',
            constraint=models.UniqueConstraint(condition=models.Q(('etapa__isnull', False), ('status__in', ['enviado', 'pulada'])), fields=('evento', 'etapa', 'data_evento_referencia'), name='uniq_envio_etapa_evento_data'),
        ),
        migrations.AddConstraint(
            model_name='enviocobranca',
            constraint=models.UniqueConstraint(condition=models.Q(('pausa__isnull', False), ('tipo__in', ['prazo_hoje', 'prazo_vencido']), ('status', 'enviado')), fields=('pausa', 'tipo'), name='uniq_envio_pausa_tipo'),
        ),
        migrations.AddConstraint(
            model_name='enviocobranca',
            constraint=models.UniqueConstraint(condition=models.Q(('ligacao__isnull', False), ('status', 'enviado')), fields=('ligacao',), name='uniq_envio_ligacao'),
        ),
    ]
