# Generated by Django 4.2.30 on 2026-05-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('atendente', 'Atendente')], default='atendente', max_length=20, verbose_name='Perfil')),
                ('password', models.CharField(max_length=256, verbose_name='Senha (hash)')),
                ('perms', models.JSONField(default=dict, verbose_name='Permissões')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'ordering': ['name'],
            },
        ),
    ]
