# Generated by Django 4.2.30 on 2026-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auth_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Token de sessão'),
        ),
    ]
