# Generated by Django 4.2.30 on 2026-08-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_criar_empresa_padrao'),
        ('usuarios', '0002_usuario_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa_ativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_com_ela_ativa', to='empresas.empresa', verbose_name='Empresa ativa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='empresas.empresa', verbose_name='Empresas vinculadas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='preferencia_tema',
            field=models.CharField(choices=[('empresa', 'Tema da empresa'), ('neutro_claro', 'Claro'), ('neutro_escuro', 'Noturno')], default='empresa', max_length=20, verbose_name='Preferência de tema'),
        ),
    ]
