# Generated by Django 4.2.30 on 2026-07-22 22:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0002_configuracaoia_importacaonotafiscal_and_more'),
        ('usuarios', '0002_usuario_auth_token'),
        ('clientes', '0002_cliente_estado_civil_cliente_nacionalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='financeiro.categoriafinanceira')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('caixa', 'Caixa')], max_length=10)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Atualizado só por MovimentoFinanceiro.registrar() — nunca gravar direto', max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores', to='financeiro.categoriafinanceira')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TelefoneAlertaFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome/label (opcional)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telefone de Alerta Financeiro',
                'verbose_name_plural': 'Telefones de Alerta Financeiro',
                'ordering': ['nome', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=160)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('nota_fiscal', 'Nota Fiscal'), ('recorrente', 'Recorrente')], default='manual', max_length=12)),
                ('anexo', models.FileField(blank=True, upload_to='financeiro/contas_pagar/%Y/%m/')),
                ('observacao', models.TextField(blank=True, default='')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.categoriafinanceira')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.fornecedor')),
                ('nota_fiscal', models.OneToOneField(blank=True, help_text='Preenchido na Fase 5 (integração com Estoque) — OneToOne garante idempotência do confirmar()', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_pagar', to='estoque.importacaonotafiscal')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebimento_ifood', models.CharField(choices=[('no_ato', 'No ato (pago direto)'), ('repasse', 'Repasse (recebido depois)')], default='no_ato', max_length=10)),
                ('dias_repasse_ifood', models.PositiveSmallIntegerField(default=30)),
                ('nota_gera_conta_pagar', models.BooleanField(default=True)),
                ('alerta_antecedencia_dias', models.PositiveSmallIntegerField(default=2)),
                ('alerta_repeticao_dias', models.PositiveSmallIntegerField(default=1)),
                ('horizonte_recorrencia_dias', models.PositiveSmallIntegerField(default=40)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_padrao_vendas', models.ForeignKey(blank=True, help_text='Destino dos movimentos automáticos de venda (PDV/iFood — Fase 4). Se vazia, os signals correspondentes logam warning e não gravam.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.contabancaria')),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
            },
        ),
        migrations.CreateModel(
            name='MovimentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_movimento', models.DateField(db_index=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='', max_length=10)),
                ('origem_tipo', models.CharField(choices=[('conta_pagar', 'Conta a Pagar'), ('conta_receber', 'Conta a Receber'), ('pdv', 'PDV'), ('ifood', 'iFood'), ('evento_pagamento', 'Pagamento de Evento'), ('manual', 'Manual')], max_length=20)),
                ('origem_id', models.CharField(blank=True, default='', max_length=64)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/%Y/%m/')),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_por_nome_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.categoriafinanceira')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='clientes.cliente')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='usuarios.usuario')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='financeiro.fornecedor')),
            ],
            options={
                'verbose_name': 'Movimento Financeiro',
                'verbose_name_plural': 'Movimentos Financeiros',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['origem_tipo', 'origem_id'], name='financeiro__origem__7dd28e_idx'), models.Index(fields=['conta', '-criado_em'], name='financeiro__conta_i_d14958_idx'), models.Index(fields=['-data_movimento'], name='financeiro__data_mo_896f00_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='movimentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('origem_tipo__in', ('pdv', 'ifood', 'evento_pagamento'))), fields=('origem_tipo', 'origem_id'), name='uniq_movimento_financeiro_origem_idempotente'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('nome', 'tipo'), name='uniq_categoria_financeira_nome_tipo'),
        ),
    ]
