# Generated by Django 4.2.30 on 2026-07-24 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaFinanceiroEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta Financeiro Enviado',
                'verbose_name_plural': 'Alertas Financeiros Enviados',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_tipo', models.CharField(choices=[('fixo', 'Fixo'), ('estimado', 'Estimado')], default='fixo', max_length=10)),
                ('dias_vencimento', models.JSONField(default=list, help_text='Lista de dias do mês (1-31), ex.: [1, 30]. Dia inexistente no mês (31 em fevereiro) cai no último dia.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despesa Recorrente',
                'verbose_name_plural': 'Despesas Recorrentes',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='despesarecorrente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_recorrentes', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='despesarecorrente',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_recorrentes', to='financeiro.fornecedor'),
        ),
        migrations.AddField(
            model_name='alertafinanceiroenviado',
            name='conta_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviados', to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='recorrente',
            field=models.ForeignKey(blank=True, help_text='Preenchida só pelo cron gerar_contas_recorrentes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.despesarecorrente'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.UniqueConstraint(condition=models.Q(('recorrente__isnull', False)), fields=('recorrente', 'data_vencimento'), name='uniq_contapagar_recorrente_vencimento'),
        ),
        migrations.AddIndex(
            model_name='alertafinanceiroenviado',
            index=models.Index(fields=['conta_pagar', '-enviado_em'], name='financeiro__conta_p_a68045_idx'),
        ),
    ]
