# Generated by Django 4.2.30 on 2026-07-24 23:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado_civil_cliente_nacionalidade_and_more'),
        ('financeiro', '0002_alertafinanceiroenviado_despesarecorrente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, unique=True)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=120)),
                ('canal', models.CharField(choices=[('ifood', 'iFood'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('referencia', models.CharField(blank=True, default='', max_length=60)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('origem_canal', models.CharField(blank=True, default='manual', max_length=20)),
                ('origem_id', models.CharField(blank=True, default='', max_length=64)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='financeiro.categoriafinanceira')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.UniqueConstraint(condition=models.Q(('origem_canal', 'manual'), _negated=True), fields=('origem_canal', 'origem_id'), name='uniq_contareceber_origem_idempotente'),
        ),
    ]
