# Generated by Django 4.2.30 on 2026-07-25 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contareceber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Opcional — ContaPagar gerada automaticamente por nota fiscal nasce sem categoria (a extração não tem como determinar uma), o usuário categoriza depois via PATCH.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.categoriafinanceira'),
        ),
    ]
