# Generated by Django 4.2.30 on 2026-07-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_auth_token'),
        ('financeiro', '0004_alter_contapagar_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoConferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldo_informado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_calculado', models.DecimalField(decimal_places=2, help_text='Snapshot de ContaBancaria.saldo_atual no momento da conferência — nunca recalculado depois', max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias', to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_saldo', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Conferência de Saldo',
                'verbose_name_plural': 'Conferências de Saldo',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
