# Generated by Django 4.2.30 on 2026-08-22 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_criar_empresa_padrao'),
        ('financeiro', '0007_popula_empresa_fase4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='empresa',
            field=models.OneToOneField(help_text='Fase 4 do multi-empresa — deixa de ser singleton global, vira 1 linha por empresa.', on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_financeira', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='empresa',
            field=models.ForeignKey(help_text='Fase 4 do multi-empresa.', on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(help_text='Fase 4 do multi-empresa.', on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(help_text='Fase 4 do multi-empresa.', on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='despesarecorrente',
            name='empresa',
            field=models.ForeignKey(help_text='Fase 4 do multi-empresa. A ContaPagar gerada pelo cron herda a empresa do molde.', on_delete=django.db.models.deletion.PROTECT, related_name='despesas_recorrentes', to='empresas.empresa'),
        ),
    ]
