# Generated by Django 4.2.30 on 2026-05-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pedidopdv',
            new_name='pdv_pedidop_status_044627_idx',
            old_name='pdv_pedido_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pedidopdv',
            new_name='pdv_pedidop_criado__ca5c43_idx',
            old_name='pdv_pedido_criado_idx',
        ),
        migrations.RenameIndex(
            model_name='produto',
            new_name='pdv_produto_ativo_c98b47_idx',
            old_name='pdv_produto_ativo_idx',
        ),
    ]
