# Generated by Django 4.2.30 on 2026-06-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_rename_pdv_pedido_status_idx_pdv_pedidop_status_044627_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel_eventos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel_ifood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel_pdv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='segmento',
            field=models.CharField(choices=[('unidade_pequena', 'Unidade Pequena'), ('unidade_media', 'Unidade Média'), ('bem_casado', 'Bem Casado'), ('bolo_encomenda', 'Bolo / Encomenda'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
    ]
