# Generated by Django 4.2.30 on 2026-07-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_produto_disponivel_eventos_produto_disponivel_ifood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaEntregaBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100, unique=True)),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taxa de Entrega por Bairro',
                'verbose_name_plural': 'Taxas de Entrega por Bairro',
                'ordering': ['bairro'],
            },
        ),
        migrations.AddField(
            model_name='pedidopdv',
            name='bairro_entrega',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
