# Generated by Django 4.2.30 on 2026-07-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0004_taxaentregabairro_pedidopdv_bairro_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete_padrao', models.DecimalField(decimal_places=2, default=0, help_text='Taxa de entrega usada quando nenhum bairro cadastrado for selecionado', max_digits=8)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Entrega',
            },
        ),
    ]
