# Generated by Django 4.2.30 on 2026-07-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
        ('pdv', '0005_configuracaoentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='margem_desejada_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Opcional. Sugere preço de venda para produtos de revenda (não substitui `preco`).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='materia_prima_origem',
            field=models.ForeignKey(blank=True, help_text='Matéria-prima da qual este produto de revenda deriva o custo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_revenda', to='fichas.materiaprima'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('fabricado', 'Fabricado'), ('revenda', 'Revenda'), ('kit', 'Kit')], db_index=True, default='fabricado', help_text='Natureza do produto: de onde vem o custo', max_length=12),
        ),
        migrations.CreateModel(
            name='DadosFiscaisProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('CENTO', 'Cento'), ('DUZIA', 'Dúzia'), ('L', 'Litro')], default='UN', max_length=6)),
                ('codigo', models.CharField(blank=True, default='', help_text='SKU interno', max_length=50)),
                ('codigo_barras', models.CharField(blank=True, default='', help_text='EAN, opcional', max_length=14)),
                ('ncm', models.CharField(blank=True, default='', max_length=10)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_fiscais', to='pdv.produto')),
            ],
            options={
                'verbose_name': 'Dados Fiscais do Produto',
            },
        ),
        migrations.CreateModel(
            name='ItemKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_kits', to='pdv.produto')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_kit', to='pdv.produto')),
            ],
            options={
                'verbose_name': 'Item do Kit',
                'unique_together': {('kit', 'componente')},
            },
        ),
        migrations.CreateModel(
            name='FaixaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_minima', models.PositiveIntegerField(help_text='A partir de quantas unidades esta faixa vale')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal', models.CharField(blank=True, choices=[('pdv', 'PDV'), ('ifood', 'iFood'), ('eventos', 'Eventos')], help_text='Vazio/null = vale para todos os canais', max_length=10, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_preco', to='pdv.produto')),
            ],
            options={
                'verbose_name': 'Faixa de Preço',
                'ordering': ['produto', 'quantidade_minima'],
                'unique_together': {('produto', 'quantidade_minima', 'canal')},
            },
        ),
    ]
