# Generated by Django 4.2.30 on 2026-07-16 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0006_produto_margem_desejada_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Limite mínimo para disparo de alerta de estoque baixo. 0 = sem alerta', max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='modo_estoque',
            field=models.CharField(blank=True, choices=[('estoque', 'Mantém estoque (produção antecipada)'), ('sob_encomenda', 'Sob encomenda (sem saldo próprio)')], help_text="Só relevante quando tipo == 'fabricado'. Revenda equivale sempre a 'estoque'; kit não usa este campo (estoque virtual).", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Saldo atual. Só é escrito quando tipo == 'revenda' ou (tipo == 'fabricado' e modo_estoque == 'estoque'). Derivado — nunca editar direto, sempre via estoque.MovimentoEstoque.registrar()", max_digits=10),
        ),
    ]
