# Generated by Django 4.2.30 on 2026-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_produto_estoque_minimo_produto_modo_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidopdv',
            name='natureza',
            field=models.CharField(choices=[('venda', 'Venda'), ('brinde', 'Brinde'), ('permuta', 'Permuta')], default='venda', max_length=10),
        ),
    ]
