# Generated by Django 4.2.30 on 2026-05-20 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido. Use o formato 000.000.000-00')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, null=True)),
                ('telefone_principal', models.CharField(max_length=20)),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ifood_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('anotaai_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TagCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor', models.CharField(default='#6366f1', max_length=7)),
                ('clientes', models.ManyToManyField(blank=True, related_name='tags', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrega', 'Entrega'), ('cobranca', 'Cobrança'), ('residencial', 'Residencial'), ('comercial', 'Comercial')], default='entrega', max_length=20)),
                ('apelido', models.CharField(blank=True, default='', help_text='Ex: Casa, Trabalho', max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('principal', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['-principal', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefone_principal'], name='clientes_cl_telefon_593e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['status'], name='clientes_cl_status_b31356_idx'),
        ),
    ]
