# Generated by Django 4.2.30 on 2026-06-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=30)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('manual', 'Envio Manual'), ('aniversario', 'Parabéns Aniversário'), ('lembrete', 'Lembrete')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falha'), ('pendente', 'Pendente')], db_index=True, default='pendente', max_length=10)),
                ('erro', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Histórico de Mensagens WhatsApp',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['tipo', 'status'], name='notificacoe_tipo_c09688_idx')],
            },
        ),
    ]
