# Generated by Django 4.2.30 on 2026-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomensagem',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Envio Manual'), ('aniversario', 'Parabéns Aniversário'), ('pedido', 'Atualização de Pedido'), ('reengajamento', 'Reengajamento'), ('lembrete', 'Lembrete')], default='manual', max_length=20),
        ),
    ]
