# Generated by Django 4.2.30 on 2026-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_add_tipos_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapi_instance_id', models.CharField(blank=True, max_length=200, verbose_name='Instance ID')),
                ('zapi_token', models.CharField(blank=True, max_length=200, verbose_name='Token')),
                ('zapi_client_token', models.CharField(blank=True, max_length=200, verbose_name='Client-Token')),
                ('notificacoes_pedido_ativo', models.BooleanField(default=True, verbose_name='Notif. de pedidos ativa')),
                ('aniversario_ativo', models.BooleanField(default=True, verbose_name='Parabéns de aniversário ativo')),
                ('reengajamento_ativo', models.BooleanField(default=True, verbose_name='Reengajamento ativo')),
                ('dias_sem_compra', models.PositiveIntegerField(default=30, verbose_name='Dias sem compra')),
                ('mensagem_aniversario', models.TextField(default='Olá, {nome}! 🎂\nA equipe Arretado Doces deseja a você um feliz aniversário!\nQue seu dia seja tão doce quanto os nossos produtos. 🍬', verbose_name='Mensagem de aniversário')),
                ('mensagem_reengajamento', models.TextField(default='Olá, {nome}! Sentimos sua falta por aqui. 🍬\nFaz um tempinho que você não aparece na Arretado Doces.\nTemos novidades esperando por você! Que tal dar uma passada?', verbose_name='Mensagem de reengajamento')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp',
            },
        ),
    ]
