# Generated by Django 4.2.30 on 2026-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_add_configuracao_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='whatsapp_conectado',
            field=models.BooleanField(default=True, verbose_name='WhatsApp conectado'),
        ),
        migrations.AddField(
            model_name='historicomensagem',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicomensagem',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('lido', 'Lido'), ('falha', 'Falha')], db_index=True, default='pendente', max_length=10),
        ),
    ]
