# Generated by Django 4.2.30 on 2026-06-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_add_webhook_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='validade_orcamento_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Validade padrão do orçamento (dias)'),
        ),
    ]
