# Generated by Django 4.2.30 on 2026-07-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_validade_orcamento_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomensagem',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Envio Manual'), ('aniversario', 'Parabéns Aniversário'), ('pedido', 'Atualização de Pedido'), ('reengajamento', 'Reengajamento'), ('lembrete', 'Lembrete'), ('orcamento', 'Orçamento PDF'), ('contrato', 'Contrato PDF')], default='manual', max_length=20),
        ),
    ]
