# Generated by Django 4.2.30 on 2026-09-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0010_alter_historicomensagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomensagem',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Envio Manual'), ('aniversario', 'Parabéns Aniversário'), ('pedido', 'Atualização de Pedido'), ('reengajamento', 'Reengajamento'), ('lembrete', 'Lembrete'), ('orcamento', 'Orçamento PDF'), ('contrato', 'Contrato PDF'), ('aditivo_contrato', 'Aditivo de Contrato PDF'), ('alerta_pagamento', 'Alerta de Pagamento Pendente'), ('alerta_entrega', 'Alerta de Entrega Próxima'), ('alerta_estoque_baixo', 'Alerta de Estoque Baixo'), ('alerta_vencimento', 'Alerta de Vencimento Financeiro'), ('backup', 'Alerta de Backup')], default='manual', max_length=20),
        ),
    ]
