# Generated by Django 4.2.30 on 2026-07-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('pasta_backup_db', models.CharField(default='/var/backups/arretado/db', max_length=255)),
                ('pasta_backup_media', models.CharField(default='/var/backups/arretado/media', max_length=255)),
                ('retencao_local_dias', models.PositiveIntegerField(default=14)),
                ('retencao_remota_dias', models.PositiveIntegerField(default=90)),
                ('rclone_remote', models.CharField(default='backup-remoto', max_length=100)),
                ('rclone_pasta_remota', models.CharField(default='arretado-backups', max_length=255)),
                ('envio_externo_ativo', models.BooleanField(default=True)),
                ('horas_limite_alerta', models.PositiveIntegerField(default=26)),
                ('tamanho_minimo_kb', models.PositiveIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
            },
        ),
        migrations.CreateModel(
            name='TelefoneAlertaBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome/label (opcional)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telefone de Alerta de Backup',
                'verbose_name_plural': 'Telefones de Alerta de Backup',
                'ordering': ['nome', 'numero'],
            },
        ),
    ]
