# Generated by Django 4.2.30 on 2026-08-10 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=80)),
                ('razao_social', models.CharField(blank=True, default='', max_length=160)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, validators=[django.core.validators.RegexValidator(message='Informe o CNPJ formatado, ex: 12.345.678/0001-90.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cor_fundo', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_surface', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_surface_alt', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_borda', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_texto', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_muted', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_primaria', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_primaria_texto', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_acento', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_sidebar', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_sidebar_texto', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('cor_sidebar_ativo', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, ex: #AE4A2A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('logo_horizontal', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('logo_negativo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('logo_simbolo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('timbre', models.FileField(blank=True, null=True, upload_to='empresas/')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-padrao', 'nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('padrao',), name='uniq_empresa_padrao'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='uniq_empresa_cnpj'),
        ),
    ]
