# Generated by Django 4.2.30 on 2026-08-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_criar_empresa_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulos_ocultos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
